### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by WaNePr** [lsdlab/80s_spider#1]
[W 190327 15:11:22 run:413] phantomjs not found, continue running without it.
[I 190327 15:11:24 result_worker:49] result_worker starting...
[I 190327 15:11:24 processor:211] processor starting...
Process Process-4:
Traceback (most recent call last):
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 236, in fetcher
    Fetcher = load_cls(None, None, fetcher_cls)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 48, in load_cls
    return utils.load_object(value)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/libs/utils.py", line 369, in load_object
    module = __import__(module_name, globals(), locals(), [object_name])
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/fetcher/__init__.py", line 1, in <module>
    from .tornado_fetcher import Fetcher
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/fetcher/tornado_fetcher.py", line 30, in <module>
    from tornado.curl_httpclient import CurlAsyncHTTPClient
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/tornado/curl_httpclient.py", line 24, in <module>
    import pycurl  # type: ignore
ImportError: dlopen(/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pycurl.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pycurl.cpython-35m-darwin.so
  Reason: image not found
[I 190327 15:11:24 scheduler:647] scheduler starting...
[I 190327 15:11:24 scheduler:782] scheduler.xmlrpc listening on 127.0.0.1:23333
[I 190327 15:11:24 scheduler:586] in 5m: new:0,success:0,retry:0,failed:0
Traceback (most recent call last):
  File "/Users/Zixuan/anaconda3/envs/py35tf/bin/pyspider", line 11, in <module>
    sys.exit(main())
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 754, in main
    cli()
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 165, in cli
    ctx.invoke(all)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 497, in all
    ctx.invoke(webui, **webui_config)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 333, in webui
    app = load_cls(None, None, webui_instance)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/run.py", line 48, in load_cls
    return utils.load_object(value)
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/libs/utils.py", line 369, in load_object
    module = __import__(module_name, globals(), locals(), [object_name])
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/webui/__init__.py", line 8, in <module>
    from . import app, index, debug, task, result, login
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/webui/app.py", line 17, in <module>
    from pyspider.fetcher import tornado_fetcher
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/fetcher/__init__.py", line 1, in <module>
    from .tornado_fetcher import Fetcher
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pyspider/fetcher/tornado_fetcher.py", line 30, in <module>
    from tornado.curl_httpclient import CurlAsyncHTTPClient
  File "/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/tornado/curl_httpclient.py", line 24, in <module>
    import pycurl  # type: ignore
ImportError: dlopen(/Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pycurl.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libssh2.1.dylib
  Referenced from: /Users/Zixuan/anaconda3/envs/py35tf/lib/python3.5/site-packages/pycurl.cpython-35m-darwin.so
  Reason: image not found

请问应该如何解决？

**Comment by lsdlab** [comment]
phantomjs 没有安装，http://phantomjs.org/download.html
